### ISSUE TITLE
Script does not enable Detective in master account

### ISSUE THREAD

**Issue by josagonzalez** [aws-samples/amazon-detective-multiaccount-scripts#3]
The documentation makes mention that the `enableDetective.py` script enables Detective for a master account across all regions. However, when running on an account without Detective enabled, the script outputs this message: `INFO - AWS Detective is NOT enabled in us-west-2`. Looking at the code, it looks like the script does not try to enable Detective in that master account at all.

**Comment by smsilb** [comment]
Hi @josagonzalez. Thanks for reporting that issue! I've opened #4 to resolve it.
