### ISSUE TITLE
enableDetective fails if tries to enable more than 50 accounts

### ISSUE THREAD

**Issue by siulpolb** [aws-samples/amazon-detective-multiaccount-scripts#6]
enableDetective script fails if CSV contains more than 50 accounts.

This is due api restriction.

The error:

ERROR - exception when getting memebers: An error occurred (ValidationException) when calling the CreateMembers operation: CreateMembersRequest.Accounts must have length less than or equal to 50. Found 100.
Traceback (most recent call last):
  File "enableDetective.py", line 259, in create_members
    response = d_client.create_members(GraphArn=graph_arn,
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the CreateMembers operation: CreateMembersRequest.Accounts must have length less than or equal to 50. Found 100.

**Comment by smsilb** [comment]
Hi @siulpolb, thanks for reporting this issue! We're tracking this issue and will report back here once it's been fixed.

**Comment by smsilb** [comment]
@siulpolb Could you pull the latest and try again? #12 is a fix for this issue.

**Comment by siulpolb** [comment]
@smsilb I don't have access to the same amount of accounts right now to test the changes

**Comment by wingamajig** [comment]
This issue has been fixed, please open a new issue if you have any problems
